<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ce24b372-6816-4f53-a727-01a25b2d22ab</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaborStats.Application\LaborStats.Application.csproj" />
    <ProjectReference Include="..\LaborStats.Domain\LaborStats.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LaborStats.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\Seed\SeedProfessionsAndGroupsData.sql">
      <LogicalName>LaborStats.Infrastructure.Data.Seed.SeedProfessionsAndGroupsData.sql</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="ExcelDataReader" />
    <PackageReference Include="ExcelDataReader.DataSet" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" />
    <PackageReference Include="FluentEmail.Smtp" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
  </ItemGroup>

</Project>
