// <auto-generated />
using System;
using LaborStats.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaborStats.Infrastructure.Migrations
{
    [DbContext(typeof(LaborStatsDbContext))]
    [Migration("20260713065615_ProfessionsAndGroups")]
    partial class ProfessionsAndGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("labor_stats")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaborStats.Domain.Entities.County", b =>
                {
                    b.Property<string>("Teryt")
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("teryt")
                        .IsFixedLength();

                    b.Property<bool>("IsCityWithCountyRights")
                        .HasColumnType("boolean")
                        .HasColumnName("is_city_with_county_rights");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("VoivodeshipTeryt")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("voivodeship_teryt")
                        .IsFixedLength();

                    b.HasKey("Teryt")
                        .HasName("pk_counties");

                    b.HasIndex("VoivodeshipTeryt")
                        .HasDatabaseName("ix_counties_voivodeship_teryt");

                    b.ToTable("counties", "geo");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.ProfessionGroups", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("created_by_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("NameEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name_en");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_name");

                    b.HasKey("Id")
                        .HasName("pk_profession_groups");

                    b.ToTable("ProfessionGroups", "prof");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Professions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuidv7()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("CreatedById")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("created_by_id");

                    b.Property<string>("CreatedByName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("")
                        .HasColumnName("created_by_name");

                    b.Property<int>("KzisCode")
                        .HasColumnType("integer")
                        .HasColumnName("kzis_code");

                    b.Property<string>("KzisName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("kzis_name");

                    b.Property<Guid>("ProfessionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("profession_group_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_name");

                    b.HasKey("Id")
                        .HasName("pk_professions");

                    b.HasIndex("ProfessionGroupId")
                        .HasDatabaseName("ix_professions_profession_group_id");

                    b.ToTable("Professions", "prof");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Voivodeship", b =>
                {
                    b.Property<string>("Teryt")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("teryt")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Teryt")
                        .HasName("pk_voivodeships");

                    b.ToTable("voivodeships", "geo");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.County", b =>
                {
                    b.HasOne("LaborStats.Domain.Entities.Voivodeship", "Voivodeship")
                        .WithMany("Counties")
                        .HasForeignKey("VoivodeshipTeryt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_counties_voivodeships_voivodeship_teryt");

                    b.Navigation("Voivodeship");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Professions", b =>
                {
                    b.HasOne("LaborStats.Domain.Entities.ProfessionGroups", "ProfessionGroup")
                        .WithMany("Professions")
                        .HasForeignKey("ProfessionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_professions_profession_groups_profession_group_id");

                    b.Navigation("ProfessionGroup");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.ProfessionGroups", b =>
                {
                    b.Navigation("Professions");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Voivodeship", b =>
                {
                    b.Navigation("Counties");
                });
#pragma warning restore 612, 618
        }
    }
}
