// <auto-generated />
using LaborStats.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LaborStats.Infrastructure.Migrations
{
    [DbContext(typeof(LaborStatsDbContext))]
    partial class LaborStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("labor_stats")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LaborStats.Domain.Entities.County", b =>
                {
                    b.Property<string>("Teryt")
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("teryt")
                        .IsFixedLength();

                    b.Property<bool>("IsCityWithCountyRights")
                        .HasColumnType("boolean")
                        .HasColumnName("is_city_with_county_rights");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("VoivodeshipTeryt")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("voivodeship_teryt")
                        .IsFixedLength();

                    b.HasKey("Teryt")
                        .HasName("pk_counties");

                    b.HasIndex("VoivodeshipTeryt")
                        .HasDatabaseName("ix_counties_voivodeship_teryt");

                    b.ToTable("counties", "geo");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Voivodeship", b =>
                {
                    b.Property<string>("Teryt")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("teryt")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Teryt")
                        .HasName("pk_voivodeships");

                    b.ToTable("voivodeships", "geo");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.County", b =>
                {
                    b.HasOne("LaborStats.Domain.Entities.Voivodeship", "Voivodeship")
                        .WithMany("Counties")
                        .HasForeignKey("VoivodeshipTeryt")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_counties_voivodeships_voivodeship_teryt");

                    b.Navigation("Voivodeship");
                });

            modelBuilder.Entity("LaborStats.Domain.Entities.Voivodeship", b =>
                {
                    b.Navigation("Counties");
                });
#pragma warning restore 612, 618
        }
    }
}
