<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="coverlet.collector" />
	  <PackageReference Include="FluentEmail.Smtp" />
	  <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" />
	  <PackageReference Include="Respawn" />
	  <PackageReference Include="Testcontainers" />
	  <PackageReference Include="Testcontainers.PostgreSql" />
	  <PackageReference Include="xunit" />
	  <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LaborStats.Api\LaborStats.Api.csproj" />
    <ProjectReference Include="..\LaborStats.Infrastructure\LaborStats.Infrastructure.csproj" />
  </ItemGroup>

</Project>